# Generated by Django 5.1.6 on 2025-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=20),
        ),
    ]
