# Generated by Django 5.1.6 on 2025-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_profile_shop_name_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
